# Generated by Django 6.0.3 on 2026-03-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
